### ISSUE TITLE
我想问下你是通过自动化的方法把md发布到知乎吗？

### ISSUE THREAD

**Issue by zhaoqingqing** [jayren3996/zhihu_articles#1]
你好，我看了下Zhihu.py的源码，是把md内容转成知乎的格式，那么我想问下你是通过自动的方法把md发布到知乎吗？

起源是我想实现自动把md文件发布到知乎上，但是找了下目前知乎没有开放接口，想问下你是怎么解决的?

**Comment by jayren3996** [comment]
你好，我现在只是用 python 脚本转换格式，还需要在知乎里用导入文档的功能发布。
另外，这个自动化脚本来源于 https://github.com/miracleyoo/Markdown4Zhihu

**Comment by zhaoqingqing** [comment]
好的，了解了。
